# Generated by Django 2.2.17 on 2021-04-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
