# Generated by Django 2.2.17 on 2021-03-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='clicker_app.Achievement'),
        ),
    ]
