# Generated by Django 2.2.17 on 2021-04-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='darkmode',
            field=models.BooleanField(default=True),
        ),
    ]
