# Generated by Django 2.2.17 on 2023-05-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0002_auto_20210405_2251'),
        ('clicker_app', '0002_auto_20210405_2152'),
    ]

    operations = [
    ]
