# Generated by Django 2.2.17 on 2021-04-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0002_account_darkmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownsupgrade',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
