# Generated by Django 2.2.17 on 2021-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0003_auto_20210403_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='condition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='current_score_achievement',
            field=models.BooleanField(default=False),
        ),
    ]
